"""Markdown report generator for UIDT PR-0 runs."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict


REPORT_HEADER = "# UIDT PR-0 Pregeometry Harness Report"


def write_report(*, project_root: Path, run_json_path: Path) -> Path:
    project_root = Path(project_root).resolve()
    run_json_path = Path(run_json_path).resolve()
    payload = json.loads(run_json_path.read_text(encoding="utf-8"))

    parameters = payload["parameters"]
    seed = parameters["seed"]
    iterations = parameters["iterations"]
    report_dir = project_root / "verification" / "pregeometry" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"pr0_report_seed{seed}_iter{iterations}.md"

    content = render_report(payload=payload, run_json_relative=str(run_json_path.relative_to(project_root)))
    report_path.write_text(content, encoding="utf-8")
    return report_path


def render_report(*, payload: Dict[str, object], run_json_relative: str) -> str:
    parameters = payload["parameters"]
    uidt = payload["uidt_toy"]
    null = payload["null_model"]
    leakage = payload["leakage_audit"]

    uidt_inv = uidt["invariants"]
    null_inv = null["invariants"]

    lines = [
        REPORT_HEADER,
        "",
        "## 1. Status",
        "",
        "This report is generated by the UIDT PR-0 pregeometry harness.",
        "",
        "All physical interpretation remains `[D/E]`.",
        "Exact graph invariant values are `[A]` only as software invariants for this executed code path.",
        "",
        "## 2. Claims Table",
        "",
        "| Claim | Status | Scope |",
        "|---|---|---|",
        "| The run computed exact graph invariants. | `[A]` | Software invariant for this execution only. |",
        "| The carrier is coordinate-free at the primitive level. | `[A]` | Checked by object structure and tests. |",
        "| The run establishes physical spacetime emergence. | Not claimed | Deferred; no metric observable in PR-0. |",
        "| The run establishes cosmological validity. | Not claimed | No empirical cosmology comparison. |",
        "| The run establishes gauge-sector emergence. | Not claimed | No gauge algebra implementation. |",
        "| The toy sector has physical interpretation. | `[D/E]` | Hypothesis-level only. |",
        "",
        "## 3. Reproduction Note",
        "",
        "Run from repository root:",
        "",
        "```bash",
        f"python -m verification.pregeometry.experiments.run_pregeometry_toy --iterations {parameters['iterations']} --seed {parameters['seed']}",
        "```",
        "",
        "Run JSON:",
        "",
        f"```text\n{run_json_relative}\n```",
        "",
        "## 4. Leakage Audit Result",
        "",
        f"Passed: `{leakage['passed']}`",
        "",
        "Scanned paths:",
        "",
    ]
    scanned_paths = leakage.get("scanned_paths", [])
    if scanned_paths:
        for path in scanned_paths:
            lines.append(f"- `{path}`")
    else:
        lines.append("- No generation files found in default scan scope.")

    lines.extend([
        "",
        "Hits:",
        "",
    ])
    hits = leakage.get("hits", [])
    if hits:
        for hit in hits:
            lines.append(f"- `{hit['path']}:{hit['line_number']}` token `{hit['token']}`")
    else:
        lines.append("- None.")

    lines.extend([
        "",
        "## 5. Exact Invariant Table",
        "",
        "| Sector | N | E | C | beta_1 |",
        "|---|---:|---:|---:|---:|",
        f"| UIDT toy | {uidt_inv['N']} | {uidt_inv['E']} | {uidt_inv['C']} | {uidt_inv['beta_1']} |",
        f"| Null model: {null['name']} | {null_inv['N']} | {null_inv['E']} | {null_inv['C']} | {null_inv['beta_1']} |",
        "",
        "## 6. Applied UIDT Toy Rules",
        "",
    ])
    for index, name in enumerate(uidt["applied_rules"]):
        lines.append(f"{index + 1}. `{name}`")

    lines.extend([
        "",
        "## 7. Negative Results and Limitations",
        "",
        "- PR-0 does not implement spectral dimension.",
        "- PR-0 does not implement curvature proxies.",
        "- PR-0 does not implement coarse-graining.",
        "- PR-0 does not implement a null-model separation score.",
        "- PR-0 does not establish metric emergence.",
        "- PR-0 does not establish cosmological validity.",
        "- PR-0 does not establish gauge-sector emergence.",
        "- A failed run falsifies only this toy sector under these registered rules and observables.",
        "",
        "## 8. Interpretation Boundary",
        "",
        "This harness tests a restricted toy sector of coordinate-free relational growth.",
        "A successful run establishes only internal reproducibility of exact graph invariants.",
        "It does not establish spacetime emergence, cosmological validity, gauge-sector emergence, or physical correctness of UIDT.",
        "A failed run falsifies only this toy sector under the registered rules and observables.",
        "",
    ])
    return "\n".join(lines)
