#!/usr/bin/env python3
"""
uv_match.py — UIDT v3.9 UV Matching & Operator-Mixing Check
Toy model: heavy fermion of mass M with Yukawa y generates S·F² at low energy.
Output: verification/data/visualizations/uv_matching.md

Evidence: [D] — prediction until independent UV model verification.
Limitation: simple 1-loop matching only; 2-loop and non-perturbative effects not included.
"""
from mpmath import mp, mpf, fabs, pi
from pathlib import Path

mp.dps = 80

KAPPA_CANONICAL = mpf("0.500")
LAMBDA_S        = mpf("0.41666666666666666666")

SCENARIOS = [
    {"label": "Benchmark",     "M": "1000", "y": "0.1",  "Lambda": "1000"},
    {"label": "Strong Yukawa", "M": "1000", "y": "1.0",  "Lambda": "1000"},
    {"label": "M=500 GeV",     "M": "500",  "y": "0.5",  "Lambda": "500"},
    {"label": "M=Delta*",      "M": "1710", "y": "0.5",  "Lambda": "1710"},
    {"label": "Large-y Limit", "M": "1000", "y": "3.14", "Lambda": "1000"},
]


def match_scenario(M: str, y: str, Lambda: str) -> dict:
    """1-loop heavy-fermion matching: C_5 = y^2 / (16π²M), κ̄ = C_5 * Λ."""
    M_v  = mpf(M)
    y_v  = mpf(y)
    L_v  = mpf(Lambda)
    C5   = y_v**2 / (16 * pi**2 * M_v)
    kb   = C5 * L_v
    d4   = y_v**2 * L_v**2 / (16 * pi**2 * M_v**2)
    d3   = y_v**2 * L_v**3 / (16 * pi**2 * M_v**3)
    rel  = fabs(kb - KAPPA_CANONICAL) / KAPPA_CANONICAL
    return {
        "M_GeV":              M,
        "y":                  y,
        "Lambda_GeV":         Lambda,
        "C5_dim5":            mp.nstr(C5, 10),
        "kappa_bar":          mp.nstr(kb, 10),
        "kappa_canonical":    mp.nstr(KAPPA_CANONICAL, 10),
        "rel_diff":           mp.nstr(rel, 8),
        "dim4_contamination": mp.nstr(d4, 8),
        "dim3_contamination": mp.nstr(d3, 8),
        "fine_tuning":        "YES" if d4 > mpf("0.01") else "NO",
        "status":             "MATCH" if rel < mpf("0.01") else "[TENSION ALERT]",
    }


def main():
    out = Path("verification/data/visualizations/uv_matching.md")
    out.parent.mkdir(parents=True, exist_ok=True)

    results = [{"label": s["label"], **match_scenario(s["M"], s["y"], s["Lambda"])}
               for s in SCENARIOS]

    lines = [
        "# UV Matching Report — UIDT v3.9\n",
        "**Evidence:** [D] prediction | **Stratum:** III (UIDT interpretation)\n",
        f"**Canonical:** κ = {mp.nstr(KAPPA_CANONICAL,10)}, λ_S = {mp.nstr(LAMBDA_S,10)}\n\n",
        "## Operator Matching Table\n",
        "| Label | M [GeV] | y | κ̄ | rel. diff. | dim-4 contam. | Fine-tuning | Status |\n",
        "|---|---|---|---|---|---|---|---|\n",
    ]
    for r in results:
        lines.append(
            f"| {r['label']} | {r['M_GeV']} | {r['y']} | {r['kappa_bar']} "
            f"| {r['rel_diff']} | {r['dim4_contamination']} | {r['fine_tuning']} | {r['status']} |\n"
        )
    lines += [
        "\n## Assessment\n",
        "- Dim-5 operator `κ/Λ · S · Tr(FF)` cannot be generated by simple heavy-fermion at O(TeV)\n",
        "  without O(1) Yukawa coupling or fine-tuning.\n",
        "- κ=0.500 requires an explicit UV symmetry argument (e.g., shift symmetry on S).\n",
        "- Fine-tuning flag (dim-4 contamination > 1%) is absent in benchmark — \n",
        "  but κ̄ ≪ κ_canonical means simple matching is insufficient.\n",
        "- [D] Falsification exposure: LHC/future S coupling inconsistent with κ=0.500.\n",
    ]

    out.write_text("".join(lines), encoding="utf-8")
    tensions = [r for r in results if "TENSION" in r["status"]]
    print(f"UV matching → {out} | Tensions: {len(tensions)}/{len(results)}")
    for r in results:
        print(f"  {r['label']:14s} κ̄={r['kappa_bar']:12s} rel={r['rel_diff']:12s} FT={r['fine_tuning']} → {r['status']}")


if __name__ == "__main__":
    main()
